# Generated by Django 4.1.1 on 2022-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('notes', models.TextField()),
                ('application_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
